### ISSUE TITLE
Empty error message

### ISSUE THREAD

**Issue by jcrmatos** [alberthdev/dummymp#1]
Hello,

Congrats, you have developed an amazing app.
I've spent countless hours trying to use the Multiprocessing module. It is a headache.

I tried to use dummymp to speedup my experimental trading search, and it works on small workloads, but it returns an error message when I increase it.

I imported your module using import dummymp as mp.

The traceback starts in my app at
mp.process_process()
then goes to
process_queue() in file ...\dummymp\taskmgr.py line 112, in process_queue()
qout = dummymp_queue.get(timeout = 0.001) in file ...\dummymp\taskmgr.py line 52, in process_queue
raise Empty in file ...\multiprocessing\queues.py line 132, in get

The final message is Queue.Empty.

Best regards,

JM

**Comment by alberthdev** [comment]
Hi there! Glad to hear that people are using this little library out there! There's definitely some interesting bugs I've found after the initial release, and I plan on fixing them sometime soon.

Could you copy and paste the traceback, and place them in a code (```) block? I know you sort of did already, but having it formatted code style really helps (along with the original traceback).

Also, what does your function do? Are you returning anything from the function at all? Does the function have any errors? (Not to say that you have code errors, but perhaps you throw a few exceptions in the function?)

Sorry if I'm asking a lot - it helps to know the full picture!

**Comment by jcrmatos** [comment]
Hello,

The traceback looks like this:

```
Traceback (most recent call last):
  File "studies.py", line 763, in <module>
    sys.exit(main())
  File "studies.py", line 519, in main
    best_combo, best_trades_df = best_tdaily_combo_mp(quotes_df)
  File "studies.py", line 310, in best_tdaily_combo_mp
    mp.process_process()
  File "C:\WinPython27\python-2.7.9\lib\site-packages\dummymp\taskmgr.py", line
112, in process_process
    process_queue()
  File "C:\WinPython27\python-2.7.9\lib\site-packages\dummymp\taskmgr.py", line
52, in process_queue
    qout = dummymp_queue.get(timeout = 0.001)
  File "C:\WinPython27\python-2.7.9\lib\multiprocessing\queues.py", line 132, in
 get
    raise Empty
Queue.Empty
```

if I comment mp.process_process() the traceback is:

```
Traceback (most recent call last):
  File "studies.py", line 763, in <module>
    sys.exit(main())
  File "studies.py", line 519, in main
    best_combo, best_trades_df = best_tdaily_combo_mp(quotes_df)
  File "studies.py", line 311, in best_tdaily_combo_mp
    mp.process_until_done()
  File "C:\WinPython27\python-2.7.9\lib\site-packages\dummymp\taskmgr.py", line
246, in process_until_done
    process_queue()
  File "C:\WinPython27\python-2.7.9\lib\site-packages\dummymp\taskmgr.py", line
52, in process_queue
    qout = dummymp_queue.get(timeout = 0.001)
  File "C:\WinPython27\python-2.7.9\lib\multiprocessing\queues.py", line 132, in
 get
    raise Empty
Queue.Empty
```

My code:

``` python
def tday_trade(quotes_df, years, buy_tday, sell_tday):
    """Simulate trading buy/sell tday for all years."""
    trades = []
    for year in years:
        buy_df = quotes_df[(quotes_df.Y == year) & (quotes_df.tD == buy_tday)]

        if not buy_df.empty:
            buy_srs = buy_df.AC

            sell_df = quotes_df[(quotes_df.Y == year) & 
                                (quotes_df.tD == sell_tday)]

            if not sell_df.empty:
                sell_srs = sell_df.AC

                # B_date, B_price, S_date, S_price, Return
                trades.append([buy_srs.index[0], buy_srs[0],
                               sell_srs.index[0], sell_srs[0],
                               sell_srs[0] - buy_srs[0]])

    return [buy_tday, sell_tday, trades]


def best_tdaily_combo_mp(quotes_df):
    """Simulate all combinations of trading days to find the best combo."""
    years = quotes_df.Y.unique()
    best_trades_df = pd.DataFrame()
    trades_dic = {}

    mp.getCPUAvail()
    mp.set_priority_mode(mp.DUMMYMP_NUCLEAR)
    mp.set_args_deepcopy(False)
    mp.set_kwargs_deepcopy(False)

    for buy_tday in range(1, 2):
        for sell_tday in range(buy_tday, 255):
            mp.run(tday_trade, quotes_df, years, buy_tday, sell_tday)
            mp.process_process()
    mp.process_until_done()
    trades_dic['results'] = mp.get_returns()
    mp.reset()
    ...
```

Function best_tdaily_combo_mp tries to find the best combination of trading days (buy/sell).
Function tday_trade is a worker for the previous function and "trades" the buy/sell combo for all years available in the quotes_df dataframe.
Line

``` python
for buy_tday in range(1, 2):
```

was supposed to be

``` python
for buy_tday in range(1, 255):
```

but I changed it to test with a single run.

Yes, the worker is returning a list with buy trade day, sell trade day and trades.

Thanks,

JM

**Comment by alberthdev** [comment]
Interesting... the Queue.Empty should never happen, since I check for emptiness in `if not dummymp_queue.empty():`...

I'm going to investigate this further. For now, let's try this...

Apply this patch (either with the patch utility or just by hand). Let me know if this fixes anything for you! (I just added a try/except around the code, catching the Queue.Empty exception.)

``` diff
diff --git a/dummymp/taskmgr.py b/dummymp/taskmgr.py
index 0fb4041..fba2659 100644
--- a/dummymp/taskmgr.py
+++ b/dummymp/taskmgr.py
@@ -47,30 +47,33 @@ def process_queue():
     for dummymp_queue in config.dummymp_queues:
         # Make sure there's something to fetch from the queue!
         if not dummymp_queue.empty():
-            # Make a request to get the queue, with a timeout to ensure
-            # no blocking (or long waiting)
-            qout = dummymp_queue.get(timeout = 0.001)
-            
-            # Check if it's a list or not
-            if type(qout) != list:
-                logger.warning("WARNING: Received invalid message from process! This may be a bug! Message: %s" % str(qout))
-                continue
-            
-            # Check the message type IDs!
-            # Format: [ [ DUMMYMP_MSG_TYPE_ID, SYSTEM_PID, INTERNAL_ID ], DATA... ]
-            if qout[0][0] == config.DUMMYMP_LOG_ID:
-                # Append PID info text
-                qout[1].msg = ("[PID %i] " % qout[0][1]) + qout[1].msg
-                # Emit the modified log record
-                # BUG: seems like logger.handle() doesn't do any
-                # filtering - therefore, we need to filter it ourselves.
-                if logger.isEnabledFor(qout[1].levelno):
-                    logger.handle(qout[1])
-            elif qout[0][0] == config.DUMMYMP_RET_ID:
-                # Store return into return dictionary
-                config.dummymp_rets[qout[0][2]] = qout[1]
-            else:
-                logger.warning("WARNING: Received invalid message from process! (Invalid message type ID!) This may be a bug! Message: %s" % str(qout))
+            try:
+                # Make a request to get the queue, with a timeout to ensure
+                # no blocking (or long waiting)
+                qout = dummymp_queue.get(timeout = 0.001)
+                
+                # Check if it's a list or not
+                if type(qout) != list:
+                    logger.warning("WARNING: Received invalid message from process! This may be a bug! Message: %s" % str(qout))
+                    continue
+                
+                # Check the message type IDs!
+                # Format: [ [ DUMMYMP_MSG_TYPE_ID, SYSTEM_PID, INTERNAL_ID ], DATA... ]
+                if qout[0][0] == config.DUMMYMP_LOG_ID:
+                    # Append PID info text
+                    qout[1].msg = ("[PID %i] " % qout[0][1]) + qout[1].msg
+                    # Emit the modified log record
+                    # BUG: seems like logger.handle() doesn't do any
+                    # filtering - therefore, we need to filter it ourselves.
+                    if logger.isEnabledFor(qout[1].levelno):
+                        logger.handle(qout[1])
+                elif qout[0][0] == config.DUMMYMP_RET_ID:
+                    # Store return into return dictionary
+                    config.dummymp_rets[qout[0][2]] = qout[1]
+                else:
+                    logger.warning("WARNING: Received invalid message from process! (Invalid message type ID!) This may be a bug! Message: %s" % str(qout))
+            except Queue.Empty:
+                pass

 def process_process():
     """Process the execution queue and inter-process messages.
```

**Comment by jcrmatos** [comment]
Hello,

Sorry for the delay.
I tested your changes and got an imediate traceback.

Here it is:

Traceback (most recent call last):
   File "studies.py", line 802, in <module>
     sys.exit(main())
   File "studies.py", line 558, in main
     best_combo, best_trades_df = best_tdaily_combo_mp(quotes_df)
   File "studies.py", line 349, in best_tdaily_combo_mp
     mp.process_process()
   File 
"C:\WinPython27\python-2.7.9\lib\site-packages\dummymp\taskmgr.py", line
139, in process_process
     process_queue()
   File 
"C:\WinPython27\python-2.7.9\lib\site-packages\dummymp\taskmgr.py", line
99, in process_queue
     except Queue.Empty:
AttributeError: 'function' object has no attribute 'Empty'

Best regards,

JM

**Comment by alberthdev** [comment]
No problem! Interesting... Queue should definitely be a 'module' object, not a function. I'm sort of perplexed as to why it's thinking Queue is a function...

Taking a shot in the dark here, but try replacing [line 24](https://github.com/alberthdev/dummymp/blob/master/dummymp/taskmgr.py#L24) from:

``` python
from multiprocessing import Process, Queue
```

...to:

``` python
from multiprocessing import Process
import Queue
```

Let me know if this fixes anything. Also, please try to place those exceptions in code blocks - they tend to be harder to read in plain! Thanks!

**Comment by jcrmatos** [comment]
Hello,

The traceback changed to:

Traceback (most recent call last):
   File "studies.py", line 893, in <module>
     sys.exit(main())
   File "studies.py", line 648, in main
     best_combo, best_trades_df = best_tdaily_combo_mp(quotes_df)
   File "studies.py", line 351, in best_tdaily_combo_mp
     mp.process_process()
   File 
"C:\WinPython27\python-2.7.9\lib\site-packages\dummymp\taskmgr.py", line
209, in process_process
     q = Queue()
TypeError: 'module' object is not callable

so I changed line 25 from
import Queue
to
from Queue import Queue

and it advanced a bit and then returned a new traceback:

Traceback (most recent call last):
   File "studies.py", line 893, in <module>
     sys.exit(main())
   File "studies.py", line 648, in main
     best_combo, best_trades_df = best_tdaily_combo_mp(quotes_df)
   File "studies.py", line 351, in best_tdaily_combo_mp
     mp.process_process()
   File 
"C:\WinPython27\python-2.7.9\lib\site-packages\dummymp\taskmgr.py", line
234, in process_process
     p.start()
   File "C:\WinPython27\python-2.7.9\lib\multiprocessing\process.py", 
line 130, i
n start
     self._popen = Popen(self)
   File "C:\WinPython27\python-2.7.9\lib\multiprocessing\forking.py", 
line 277, i
n __init__
     dump(process_obj, to_child, HIGHEST_PROTOCOL)
   File "C:\WinPython27\python-2.7.9\lib\multiprocessing\forking.py", 
line 199, i
n dump
     ForkingPickler(file, protocol).dump(obj)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 224, in dump
     self.save(obj)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 331, in save
     self.save_reduce(obj=obj, *rv)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 419, in 
save_reduce
     save(state)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 286, in save
     f(self, obj) # Call unbound method with explicit self
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 649, in save_dict
     self._batch_setitems(obj.iteritems())
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 681, in 
_batch_setitems

```
 save(v)
```

   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 286, in save
     f(self, obj) # Call unbound method with explicit self
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 562, in save_tuple
     save(element)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 286, in save
     f(self, obj) # Call unbound method with explicit self
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 725, in save_inst
     save(stuff)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 286, in save
     f(self, obj) # Call unbound method with explicit self
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 649, in save_dict
     self._batch_setitems(obj.iteritems())
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 681, in 
_batch_setitems

```
 save(v)
```

   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 331, in save
     self.save_reduce(obj=obj, *rv)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 396, in 
save_reduce
     save(cls)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 286, in save
     f(self, obj) # Call unbound method with explicit self
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 748, in 
save_global
     (obj, module, name))
pickle.PicklingError: Can't pickle <type 'thread.lock'>: it's not found 
as threa
d.lock

C:\Users\JMatos\MEOCloud\Python\ml4stocks\ml4stocks>Traceback (most 
recent call
last):
   File "<string>", line 1, in <module>
   File "C:\WinPython27\python-2.7.9\lib\multiprocessing\forking.py", 
line 381, i
n main
     self = load(from_parent)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 1378, in load
     return Unpickler(file).load()
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 858, in load
     dispatch[key](self)
   File "C:\WinPython27\python-2.7.9\lib\pickle.py", line 880, in load_eof
     raise EOFError
EOFError

Best regards,

JM

**Comment by alberthdev** [comment]
Would you mind sending me your source, if possible? If it's not open source, that's totally fine - I can give you my email and you can send it to me there. I'd like to test and debug on my local machine, since this seems to be an odd problem!
